import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

const opensans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nexcent',
  description: 'Generated by Gian',
  icons: 'favicon.png',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={opensans.className}>{children}</body>
    </html>
  )
}
